base_url = "-"
compile_sass = true
title = "-"
description = "A clean resume theme"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "-"
last_name = "-"
address = "-"
email = "-"
# favicon = "/favicon.ico"
# avatar = "/media/avatar.png"

katex = false
show_about = true
show_blog = true
show_inventory = true
