name = "-"
description = "-"
license = "-"
homepage = "-"
min_version = "0.11.0"
demo = "-"

compile_sass = true
generate_feed = true

taxonomies = [
  { name = "tags", feed = true },
]

[extra]
first_name = "-"
last_name = "-"
address = "-"
email = "-"
favicon = "-"
avatar = "-"

katex = false
show_about = true
show_blog = true

[author]
name = "-"
homepage = "-"

[original]
author =  "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"
repo = "https://github.com/getzola/hyde"
